export interface IAnimation {
    animId: number;
    id: number;
    library: string;
    name: string;
    vel: number;
    aLoop: number;
    lockX: number;
    lockY: number;
    freeze: number;
    lp: number;
    car: number;
    psAnim: number;
}


export const ANIMATION_CATEGORIES = [
  "SENTARSE", "POSE_MODELO", "MASTICAR", "VOMITAR", "ASUSTARSE", "SENTADO_BURGER", "BANDEJA", "CAER", "DORMIR", "BAR", "ESCUCHAR", "BATEAR", "GOLPEADO", "ADIÓS", "BALCÓN", "LAVAR_MANOS", "TUMBARSE", "PRESS_BANCA", "RAP", "BOMBA", "CARGAR_CAJA", "BASKET", "PERDER", "GANAR", "ESCOPETA", "CÁMARA", "REVISAR_COCHE", "DAR_SALIDA", "SACAR_MANO_COCHE", "HABLAR_COCHE", "CASINO", "TOCAR", "TORTA_CULO", "MOTOSIERRA", "ECHAR_UN_VISTAZO", "MIRARSE_ROPA", "PISTOLA", "CAJÓN", "CRUZAR_BRAZOS", "MIRAR_RELOJ", "PENSAR", "AFIRMAR", "NEGAR", "VIGILAR", "APUNTAR", "CAJERO", "GOLPEAR", "TECLEAR_TELÉFONO", "GATEAR", "FORCEJEAR", "EMPUJAR", "CUBRIRSE", "ESQUIVAR", "BAILAR", "AGARRARSE", "SALTAR_AL_SUELO", "FUCK", "ATAQUE_DE_GAS", "LEVANTARSE", "MANOS_ARRIBA", "CABEZAZO", "CHARLAR", "LLAMAR_TAXI", "CANSADO", "SACAR_TELÉFONO", "GUARDAR_TELÉFONO", "APARTAR_MULTITUD", "BORRACHO", "TELÉFONO_ATENDER", "ANDAR", "PREPARAR_ARMA", "AVANZAR_PESADA", "TEST2", "AMENAZAR_BATE", "HERIDO", "CONSOLA", "SALTO_PISCINA", "SALTO_MURO", "TRATAR", "CRUZAR_MANOS", "BOXEO", "KICKBOXING", "CHIQUITO_LA_CALZADA", "PELEA_CALLEJERA", "PUÑETAZO", "PATADA", "BEBER", "SALUDAR", "DAR_MANO", "APOYARSE", "HABLAR_GANG", "CHOCAR_MANO", "DAR_MANO_1", "CHOCARSE", "CAMINAR_CUCLILLAS", "ABOFETEAR", "LEVANTAR_PESAS", "GESTO_GANG", "MIRAR_PRISMÁTICOS", "LLORAR", "LANZAR", "SACO_GOLPEAR", "PEDALEAR_GIMNASIO", "CORRER_CINTA", "CORTAR_PELO", "SOBREDOSIS", "TECLEAR_SENTADO", "BEBER_SENTADO", "BUSCAR_ESTANTERÍA", "LIGAR", "REGALAR", "BESAR", "DEGOLLAR", "APUÑALAR", "GOGO", "LOWRIDER", "RECUPERARSE", "DROGADO", "REANIMAR", "MOTORISTA", "APORREAR_PUERTA", "POSAR_MALETÍN", "SEÑALAR_DERECHA", "SEÑALAR_IZQUIERDA", "RECOGER_PELOTA", "SAMURAI", "ARREGLAR_RUEDA", "FACEPALM", "RASCARSE", "TAICHI", "GRITO", "PREOCUPADO", "NAZI", "LLAMAR_ATENCIÓN", "VENTANILLA_BANCO", "DISCUTIR", "AVANZAR_POL", "TRÁFICO", "CACHEADO", "TEST_1", "PAJA", "CORRERSE", "RODAR", "SUJETADO", "BILLAR", "REIR", "ENFADADO", "QUE_TE_DEN", "ANIMAR", "MALETA_GUARDAR", "VÁMONOS", "SÚBELO", "BÁJALO", "PINCHAR_DJ", "CUBRIR_ROSTRO", "FUMAR", "SPRAY", "STRIP", "TOMAR_SOL", "VE_ALLÍ", "PARARSE", "SWAT", "AFECTO", "ESPADA", "SUBFUSIL", "ASOMARSE", "LIMPIAR_VENTANA", "COGER_SUELO", "DILDO_SEX", "ORAL_SEX"
] as const;


export type AnimationCategory = typeof ANIMATION_CATEGORIES[number];


export const deltaSpeed = 4.1;